source "https://rubygems.org"

# Jekyll version
gem "jekyll", "~> 4.2.0"

# Theme
gem "jekyll-theme-primer"

# Jekyll plugins
group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.12"
  gem "jekyll-seo-tag", "~> 2.6"
  gem "jekyll-sitemap", "~> 1.4"
  gem "jekyll-github-metadata", "~> 2.13"